coverage:
  precision: 2
  round: down
  range: "90...100"

ignore:
  - "sslcontext-kickstart/src/main/java/nl/altindag/sslcontext/exception/GenericKeyStoreException.java"
  - "sslcontext-kickstart/src/main/java/nl/altindag/sslcontext/exception/GenericSSLContextException.java"
