language: java
os: linux
sudo: true
install: true
jdk:
  - oraclejdk8
  - openjdk11
  - openjdk15

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master


jobs:
  include:
    - stage: "build"
    - script: "mvn clean install"
