name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: print Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean verify --no-transfer-progress

  docker_based_builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ 'bellsoft/liberica-openjdk-alpine:17', 'bellsoft/liberica-openjdk-debian:17', 'git' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build with Maven
        run: ./build-in-docker.sh $image ./mvnw clean verify --no-transfer-progress -Dlicense.skip=true

  code-quality-and-coverage-scan:
    if: ${{ (github.actor == 'Hakky54') }}
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'

      - name: Build, test and quality scan
        run: mvn clean verify sonar:sonar -Dsonar.projectName=sslcontext-kickstart-parent -Dsonar.organization=hakky54 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --no-transfer-progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
